// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'zakat_calculator_notifier.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$ZakatFormDataImpl _$$ZakatFormDataImplFromJson(Map<String, dynamic> json) =>
    _$ZakatFormDataImpl(
      name: json['name'] as String? ?? '',
      email: json['email'] as String? ?? '',
      phone: json['phone'] as String? ?? '',
      country: json['country'] as String? ?? '',
      city: json['city'] as String? ?? '',
      address: json['address'] as String? ?? '',
      madhab: json['madhab'] as String? ?? 'Hanafi',
      hawlStartDate: DateTime.parse(json['hawlStartDate'] as String),
      currency: json['currency'] as String? ?? 'USD',
      cashInHand: (json['cashInHand'] as num?)?.toDouble() ?? 0.0,
      bankSavings: (json['bankSavings'] as num?)?.toDouble() ?? 0.0,
      bankChecking: (json['bankChecking'] as num?)?.toDouble() ?? 0.0,
      fixedDeposits: (json['fixedDeposits'] as num?)?.toDouble() ?? 0.0,
      foreignCurrency: (json['foreignCurrency'] as num?)?.toDouble() ?? 0.0,
      digitalWallets: (json['digitalWallets'] as num?)?.toDouble() ?? 0.0,
      cryptocurrencies: (json['cryptocurrencies'] as num?)?.toDouble() ?? 0.0,
      goldWeightGrams: (json['goldWeightGrams'] as num?)?.toDouble() ?? 0.0,
      goldCurrentPrice: (json['goldCurrentPrice'] as num?)?.toDouble() ?? 0.0,
      goldJewelry: (json['goldJewelry'] as num?)?.toDouble() ?? 0.0,
      goldCoins: (json['goldCoins'] as num?)?.toDouble() ?? 0.0,
      goldBars: (json['goldBars'] as num?)?.toDouble() ?? 0.0,
      goldETFs: (json['goldETFs'] as num?)?.toDouble() ?? 0.0,
      silverWeightGrams: (json['silverWeightGrams'] as num?)?.toDouble() ?? 0.0,
      silverCurrentPrice:
          (json['silverCurrentPrice'] as num?)?.toDouble() ?? 0.0,
      silverJewelry: (json['silverJewelry'] as num?)?.toDouble() ?? 0.0,
      silverCoins: (json['silverCoins'] as num?)?.toDouble() ?? 0.0,
      silverBars: (json['silverBars'] as num?)?.toDouble() ?? 0.0,
      silverETFs: (json['silverETFs'] as num?)?.toDouble() ?? 0.0,
      businessInventory: (json['businessInventory'] as num?)?.toDouble() ?? 0.0,
      accountsReceivable:
          (json['accountsReceivable'] as num?)?.toDouble() ?? 0.0,
      rawMaterials: (json['rawMaterials'] as num?)?.toDouble() ?? 0.0,
      finishedGoods: (json['finishedGoods'] as num?)?.toDouble() ?? 0.0,
      workInProgress: (json['workInProgress'] as num?)?.toDouble() ?? 0.0,
      businessCash: (json['businessCash'] as num?)?.toDouble() ?? 0.0,
      tradingStocks: (json['tradingStocks'] as num?)?.toDouble() ?? 0.0,
      stocks: (json['stocks'] as num?)?.toDouble() ?? 0.0,
      bonds: (json['bonds'] as num?)?.toDouble() ?? 0.0,
      mutualFunds: (json['mutualFunds'] as num?)?.toDouble() ?? 0.0,
      etfs: (json['etfs'] as num?)?.toDouble() ?? 0.0,
      commodities: (json['commodities'] as num?)?.toDouble() ?? 0.0,
      retirementFunds: (json['retirementFunds'] as num?)?.toDouble() ?? 0.0,
      pensionFunds: (json['pensionFunds'] as num?)?.toDouble() ?? 0.0,
      islamicBonds: (json['islamicBonds'] as num?)?.toDouble() ?? 0.0,
      rentalProperties: (json['rentalProperties'] as num?)?.toDouble() ?? 0.0,
      commercialProperties:
          (json['commercialProperties'] as num?)?.toDouble() ?? 0.0,
      landForInvestment: (json['landForInvestment'] as num?)?.toDouble() ?? 0.0,
      reitShares: (json['reitShares'] as num?)?.toDouble() ?? 0.0,
      annualRentalIncome:
          (json['annualRentalIncome'] as num?)?.toDouble() ?? 0.0,
      grains: (json['grains'] as num?)?.toDouble() ?? 0.0,
      fruits: (json['fruits'] as num?)?.toDouble() ?? 0.0,
      vegetables: (json['vegetables'] as num?)?.toDouble() ?? 0.0,
      dates: (json['dates'] as num?)?.toDouble() ?? 0.0,
      olives: (json['olives'] as num?)?.toDouble() ?? 0.0,
      farmingEquipment: (json['farmingEquipment'] as num?)?.toDouble() ?? 0.0,
      harvestValue: (json['harvestValue'] as num?)?.toDouble() ?? 0.0,
      irrigationType: json['irrigationType'] as String? ?? 'natural',
      camels: (json['camels'] as num?)?.toInt() ?? 0,
      cattle: (json['cattle'] as num?)?.toInt() ?? 0,
      buffalo: (json['buffalo'] as num?)?.toInt() ?? 0,
      sheep: (json['sheep'] as num?)?.toInt() ?? 0,
      goats: (json['goats'] as num?)?.toInt() ?? 0,
      livestockValue: (json['livestockValue'] as num?)?.toDouble() ?? 0.0,
      isGrazing: json['isGrazing'] as bool? ?? true,
      loansGiven: (json['loansGiven'] as num?)?.toDouble() ?? 0.0,
      securityDeposits: (json['securityDeposits'] as num?)?.toDouble() ?? 0.0,
      insuranceMaturity: (json['insuranceMaturity'] as num?)?.toDouble() ?? 0.0,
      intellectualProperty:
          (json['intellectualProperty'] as num?)?.toDouble() ?? 0.0,
      otherInvestments: (json['otherInvestments'] as num?)?.toDouble() ?? 0.0,
      personalLoans: (json['personalLoans'] as num?)?.toDouble() ?? 0.0,
      creditCardDebt: (json['creditCardDebt'] as num?)?.toDouble() ?? 0.0,
      mortgageDebt: (json['mortgageDebt'] as num?)?.toDouble() ?? 0.0,
      businessLoans: (json['businessLoans'] as num?)?.toDouble() ?? 0.0,
      overdrafts: (json['overdrafts'] as num?)?.toDouble() ?? 0.0,
      accruedExpenses: (json['accruedExpenses'] as num?)?.toDouble() ?? 0.0,
      taxesOwed: (json['taxesOwed'] as num?)?.toDouble() ?? 0.0,
      otherDebts: (json['otherDebts'] as num?)?.toDouble() ?? 0.0,
      includeMortgage: json['includeMortgage'] as bool? ?? false,
      currentGoldPrice: (json['currentGoldPrice'] as num?)?.toDouble() ?? 0.0,
      currentSilverPrice:
          (json['currentSilverPrice'] as num?)?.toDouble() ?? 0.0,
      metalPricesUpdated: json['metalPricesUpdated'] == null
          ? null
          : DateTime.parse(json['metalPricesUpdated'] as String),
      notes: json['notes'] as String?,
    );

Map<String, dynamic> _$$ZakatFormDataImplToJson(_$ZakatFormDataImpl instance) =>
    <String, dynamic>{
      'name': instance.name,
      'email': instance.email,
      'phone': instance.phone,
      'country': instance.country,
      'city': instance.city,
      'address': instance.address,
      'madhab': instance.madhab,
      'hawlStartDate': instance.hawlStartDate.toIso8601String(),
      'currency': instance.currency,
      'cashInHand': instance.cashInHand,
      'bankSavings': instance.bankSavings,
      'bankChecking': instance.bankChecking,
      'fixedDeposits': instance.fixedDeposits,
      'foreignCurrency': instance.foreignCurrency,
      'digitalWallets': instance.digitalWallets,
      'cryptocurrencies': instance.cryptocurrencies,
      'goldWeightGrams': instance.goldWeightGrams,
      'goldCurrentPrice': instance.goldCurrentPrice,
      'goldJewelry': instance.goldJewelry,
      'goldCoins': instance.goldCoins,
      'goldBars': instance.goldBars,
      'goldETFs': instance.goldETFs,
      'silverWeightGrams': instance.silverWeightGrams,
      'silverCurrentPrice': instance.silverCurrentPrice,
      'silverJewelry': instance.silverJewelry,
      'silverCoins': instance.silverCoins,
      'silverBars': instance.silverBars,
      'silverETFs': instance.silverETFs,
      'businessInventory': instance.businessInventory,
      'accountsReceivable': instance.accountsReceivable,
      'rawMaterials': instance.rawMaterials,
      'finishedGoods': instance.finishedGoods,
      'workInProgress': instance.workInProgress,
      'businessCash': instance.businessCash,
      'tradingStocks': instance.tradingStocks,
      'stocks': instance.stocks,
      'bonds': instance.bonds,
      'mutualFunds': instance.mutualFunds,
      'etfs': instance.etfs,
      'commodities': instance.commodities,
      'retirementFunds': instance.retirementFunds,
      'pensionFunds': instance.pensionFunds,
      'islamicBonds': instance.islamicBonds,
      'rentalProperties': instance.rentalProperties,
      'commercialProperties': instance.commercialProperties,
      'landForInvestment': instance.landForInvestment,
      'reitShares': instance.reitShares,
      'annualRentalIncome': instance.annualRentalIncome,
      'grains': instance.grains,
      'fruits': instance.fruits,
      'vegetables': instance.vegetables,
      'dates': instance.dates,
      'olives': instance.olives,
      'farmingEquipment': instance.farmingEquipment,
      'harvestValue': instance.harvestValue,
      'irrigationType': instance.irrigationType,
      'camels': instance.camels,
      'cattle': instance.cattle,
      'buffalo': instance.buffalo,
      'sheep': instance.sheep,
      'goats': instance.goats,
      'livestockValue': instance.livestockValue,
      'isGrazing': instance.isGrazing,
      'loansGiven': instance.loansGiven,
      'securityDeposits': instance.securityDeposits,
      'insuranceMaturity': instance.insuranceMaturity,
      'intellectualProperty': instance.intellectualProperty,
      'otherInvestments': instance.otherInvestments,
      'personalLoans': instance.personalLoans,
      'creditCardDebt': instance.creditCardDebt,
      'mortgageDebt': instance.mortgageDebt,
      'businessLoans': instance.businessLoans,
      'overdrafts': instance.overdrafts,
      'accruedExpenses': instance.accruedExpenses,
      'taxesOwed': instance.taxesOwed,
      'otherDebts': instance.otherDebts,
      'includeMortgage': instance.includeMortgage,
      'currentGoldPrice': instance.currentGoldPrice,
      'currentSilverPrice': instance.currentSilverPrice,
      'metalPricesUpdated': instance.metalPricesUpdated?.toIso8601String(),
      'notes': instance.notes,
    };
